<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>WechatDuokai.Tests</AssemblyName>
    <RootNamespace>WechatDuokai.Tests</RootNamespace>
    <PlatformTarget>x64</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
    <LangVersion>latest</LangVersion>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\core\WechatDuokai.Core.csproj" />
    <ProjectReference Include="..\duokai\duokai.csproj" />
    <ProjectReference Include="..\installer\installer.csproj" />
  </ItemGroup>
</Project>
